### ISSUE TITLE
broadpeak calling is off

### ISSUE THREAD

**Issue by fanying2015** [kundajelab/atac_dnase_pipelines#114]
The pipeline seems to be working fine generally, but I can't get any broadpeaks or gapped peaks after finishing the whole pipeline.

--------------------Stderr--------------------
INFO  @ Wed, 09 May 2018 06:23:35: 
# Command line: callpeak -t /pbtech_mounts/khuranalab_scratch_athena/fta2001/Flow/Flow/ATAC_ENCODE_Pipeline_mouse/1/out/align/rep1/Chr3164_EYFP-1_AT_A12_TGCTGGGT_IGO_08155_3_S34_R1_001.trim.PE2SE.nodup.tn5.tagAlign.gz -f BED -n /pbtech_mounts/khuranalab_scratch_athena/fta2001/Flow/Flow/ATAC_ENCODE_Pipeline_mouse/1/out/peak/macs2/rep1/Chr3164_EYFP-1_AT_A12_TGCTGGGT_IGO_08155_3_S34_R1_001.trim.PE2SE.nodup.tn5.pf -g mm -p 0.01 --nomodel --shift -75 --extsize 150 -B --SPMR --keep-dup all --call-summits
# ARGUMENTS LIST:
# name = /pbtech_mounts/khuranalab_scratch_athena/fta2001/Flow/Flow/ATAC_ENCODE_Pipeline_mouse/1/out/peak/macs2/rep1/Chr3164_EYFP-1_AT_A12_TGCTGGGT_IGO_08155_3_S34_R1_001.trim.PE2SE.nodup.tn5.pf
# format = BED
# ChIP-seq file = ['/pbtech_mounts/khuranalab_scratch_athena/fta2001/Flow/Flow/ATAC_ENCODE_Pipeline_mouse/1/out/align/rep1/Chr3164_EYFP-1_AT_A12_TGCTGGGT_IGO_08155_3_S34_R1_001.trim.PE2SE.nodup.tn5.tagAlign.gz']
# control file = None
# effective genome size = 1.87e+09
# band width = 300
# model fold = [5, 50]
# pvalue cutoff = 1.00e-02
# qvalue will not be calculated and reported as -1 in the final output.
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
# Paired-End mode is off
# Searching for subpeak summits is on
# MACS will save fragment pileup signal per million reads
 
I've ran some debugged codes as suggested in other issues. The result is attached.

Thanks!!

<img width="711" alt="screen shot 2018-05-14 at 12 37 33 am" src="https://user-images.githubusercontent.com/13603229/39978518-088364c4-570f-11e8-86c4-e08b3bdb47c0.png">

**Comment by fanying2015** [comment]
The StdErr message of the whole pipeline is attached here.
Thanks!
[ATAC_ENCODE_Pipeline_mouse.1.bsub.txt](https://github.com/kundajelab/atac_dnase_pipelines/files/1999388/ATAC_ENCODE_Pipeline_mouse.1.bsub.txt)

**Comment by akundaje** [comment]
This is by design. The broad and gapped peak implementation is very flawed
in MACS2 and gives incoherent results. So we don't support it any more.

We will be providing another strategy to call broad peaks in the near
future.

Anshul.

On May 13, 2018 9:48 PM, "fanying2015" <notifications@github.com> wrote:

The StdErr message of the whole pipeline is attached here.
Thanks!
ATAC_ENCODE_Pipeline_mouse.1.bsub.txt
<https://github.com/kundajelab/atac_dnase_pipelines/files/1999388/ATAC_ENCODE_Pipeline_mouse.1.bsub.txt>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kundajelab/atac_dnase_pipelines/issues/114#issuecomment-388696148>,
or mute the thread
