### ISSUE TITLE
error running on DNANexus platform

### ISSUE THREAD

**Issue by llz-hiv** [kundajelab/atac_dnase_pipelines#137]
Hi, 

an error issue was reported when I ran the ENCODE ATAC pipeline on DNANexus platform. I had ran the pipeline on DNANexus platform before, everything was ok. I don't know why some errors were occurred this time.

The following steps were failed:
if(enable_idr)
if(!align_only && !true_rep_only && enable_idr)
qc_report
scatter(I in range (length(fastqs_ataqc)))
outputs

 
the error information is: "Failed to find index Success(WomInteger(0)) on array: Success([]) 0".

Below is the detailed log showed on platform:
[DNANexus Log.docx](https://github.com/kundajelab/atac_dnase_pipelines/files/2353793/DNANexus.Log.docx)

**Comment by leepc12** [comment]
Can you try with the latest pipeline which uses a pipeline docker container v1.1? Also, please upload all .qc files on your output directories. These will be helpful for debugging.

This repo has been deprecated. We can still discuss this issue here but next time post an issue on the new pipeline repo https://github.com/ENCODE-DCC/atac-seq-pipeline/.
