### ISSUE TITLE
error in plotGC function

### ISSUE THREAD

**Issue by victor2410** [kundajelab/atac_dnase_pipelines#39]
Hi
Thank you for this pipeline, I've tried to use it on my own data but unfortunately I get some errors while using the plotGC function in the pipeline after the idr_analysis checkpoint. It seems to be some python type conversion but I can't fix it this is the error message I get: 
`processing chromosomes
		Traceback (most recent call last):
		  File "/home/stage/atac_dnase_pipelines/ataqc/run_ataqc.py", line 1597, in <module>
		    main()
		  File "/home/stage/atac_dnase_pipelines/ataqc/run_ataqc.py", line 1546, in main
		    ('gc_bias', plot_gc(gc_out)),
		  File "/home/stage/atac_dnase_pipelines/ataqc/run_ataqc.py", line 213, in plot_gc
		    data = np.loadtxt(fp, skiprows=1)
		  File "/home/stage/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 985, in loadtxt
		    items = [conv(val) for (conv, val) in zip(converters, vals)]
		  File "/home/stage/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 687, in floatconv
		    return float(x)
		ValueError: invalid literal for float(): 0,181198`
This is the command I use from my shell terminal:
`bds atac_dnase_pipelines/atac.bds -out_dir /MyDIr/FASTQ/ATAC/MM1S_rep1.fastq.gz -fastq2 /MyDIr//FASTQ/ATAC/MM1S_rep2.fastq.gz -species hg19 -no_xcor`
I think I should replace the "," with "." but do you have an idea of what this value stand for and where I can fix it?

**Comment by vervacity** [comment]
Hi, could you post a snippet of your GC out file (should end in `_gc.txt` in the `qc` folder). From what you've given me, it looks like your PICARD is set up to output commas instead of periods? I'm not personally sure of how to fix that, but you may want to go into your system to make sure the output string for the decimal place is a period instead of a comma (switch language locale to US english). But do post the output snippet and I'll take a look.

**Comment by victor2410** [comment]
Hi!
Thank you for your answer, you were right, looking at my GC out file, all the decimal were periods, I switch language and now it perfectly work.
Thank you for your help
