### ISSUE TITLE
ataqc error in hg38: tn5.tagAlign.gz has inconsistent naming convention for record

### ISSUE THREAD

**Issue by jenchien** [kundajelab/atac_dnase_pipelines#41]
Hi kundajelab,

Thanks again for updating and maintaining the pipeline. I have got it working on my dataset using hg19, and would like to redo it using hg38. However, it exit with error in the ataqc like below:

> pybedtools.helpers.BEDToolsError: 
		Command was:
		
			bedtools intersect -c -b /osc-fs_home/chang-j/seqdata/EMT/2_WTplus/align/rep2/2_WTplus_rep2.trim.nodup.tn5.tagAlign.gz -a /tmp/pybedtools.KggEsK.tmp
		
		Error message was:
		***** WARNING: File /osc-fs_home/chang-j/seqdata/EMT/2_WTplus/align/rep2/2_WTplus_rep2.trim.nodup.tn5.tagAlign.gz has inconsistent naming convention for record:
		GL000008.2	41	88	N	1000	+
		
		***** WARNING: File /osc-fs_home/chang-j/seqdata/EMT/2_WTplus/align/rep2/2_WTplus_rep2.trim.nodup.tn5.tagAlign.gz has inconsistent naming convention for record:
		GL000008.2	41	88	N	1000	+

Is it due to the unmatched genome name between ataqc resources data and genome file for aligning? Is there a workaround way? I'm also attaching the full stdout. [atac.bds.log.txt](https://github.com/kundajelab/atac_dnase_pipelines/files/838121/atac.bds.log.txt)

Thank you.

**Comment by vervacity** [comment]
Hi,

Thanks for sharing the error. It turns out that there is a difference in annotation between the `hg38` and `hg38_ENCODE` set, which is leading to the error. The code should run through normally if you use `hg38`.

This leaves you with a few options:
1) Run hg38 through with ATAqC - this would give you the ATAqC output on hg38, but would not be exactly matching the ENCODE pipeline, if that matters to you. The output should not be very different.
2) Run hg38_ENCODE but without ATAqC. Since you've run the data through hg19, presumably you already know your QC metrics, and they won't really change (in terms of the actual data quality) by moving to hg38. So you can run the ENCODE pipeline with hg38 and get all outputs matched to the ENCODE version of the pipeline.

We are intending to push an annotation fix for this issue, but I think you could definitely continue forward with your analysis without waiting on us. But do keep an eye on the pipeline if you're interested in ATAqC on hg38_ENCODE.

Hope that makes sense!

**Comment by jenchien** [comment]
Hi,

Thanks for the prompt reply. However the genome version I used and got error was `hg38` instead of `hg38_ENCODE`. You're right since I've got ataqc result for hg19 so I know the data quality. I'll continue the downstream analysis using the hg38 output but also be looking forward for the fix.

**Comment by vervacity** [comment]
Hi,

We've put in a fix that should make the ATAqC module work for both `hg38` and `hg38_ENCODE`. (In brief, we added a `-nonamecheck` flag to bedtools so that it ignores the noncanonical chromosomes that are often named slightly differently across different genomes, even within different hg38 versions! Since this is just QC, we can afford to drop noncanonical chromosomes for QC analysis since they won't really change the QC metrics, and you get to keep them if you need them for downstream analyses) Go ahead and give it a try, and please do let us know if you run into other issues on this!

**Comment by jenchien** [comment]
Hi,

Thanks. I `git pull` the latest commit <https://github.com/kundajelab/atac_dnase_pipelines/commit/168b14ba3518c0ee431aa9306eea2b2e5d2424d8> and reran the pipeline, but encountered another error which I'm not sure if it is related.

```
                # SYS command. line 146

                 TASKTIME=$[$(date +%s)-${STARTTIME}]; echo "Task has finished (${TASKTIME} seconds)."
        StdErr (100000000 lines)  :
                usage: run_ataqc.py [-h] [--workdir WORKDIR] [--outdir OUTDIR]
                                    [--outprefix OUTPREFIX] [--genome GENOME] [--ref REF]
                                    [--tss TSS] [--dnase DNASE] [--blacklist BLACKLIST]
                                    [--prom PROM] [--enh ENH] [--reg2map_bed REG2MAP_BED]
                                    [--reg2map REG2MAP] [--meta META] [--pipeline PIPELINE]
                                    [--inprefix INPREFIX] [--fastq1 FASTQ1] [--fastq2 FASTQ2]
                                    [--alignedbam ALIGNEDBAM] [--alignmentlog ALIGNMENTLOG]
                                    [--coordsortbam COORDSORTBAM] [--duplog DUPLOG]
                                    [--pbc PBC] [--finalbam FINALBAM] [--finalbed FINALBED]
                                    [--bigwig BIGWIG] [--peaks PEAKS]
                                    [--naive_overlap_peaks NAIVE_OVERLAP_PEAKS]
                                    [--idr_peaks IDR_PEAKS] [--use_sambamba_markdup]
                run_ataqc.py: error: unrecognized arguments: --chromsizes /osc-fs_home/chang-j/seqdata//hg38/hg38.chrom.sizes

Fatal error: /osc-fs_home/chang-j/software/atac_dnase_pipelines/atac.bds, line 1457, pos 2. Task/s failed.

Creating checkpoint file: Config or command line option disabled checkpoint file creation, nothing done.
```

Here is the log file of the run. 
[atac.bds.teelog.aftergitpull.txt](https://github.com/kundajelab/atac_dnase_pipelines/files/884738/atac.bds.teelog.aftergitpull.txt)

**Comment by leepc12** [comment]
ATAQC is a submodule. Please `git pull --recurse-submodules` or remove old repo and then `git clone --recursive`.

**Comment by jenchien** [comment]
Thank you so much. Now ATAQC works for `hg38` as well as `mm10` on my side.
