### ISSUE TITLE
Bowtie and dedup options

### ISSUE THREAD

**Issue by rbronste** [kundajelab/atac_dnase_pipelines#60]
Hi,

A couple of questions:

1. In the alignment I usually add -- no-mixed --no-discordant to my Bowtie2 settings, how can I go about doing this in the pipeline? 
2. Is the duplicate and mitochondrial read removal by Picard done in one step, trying to separate the two and just do a duplicate removal. 

Thanks.

Rob.

**Comment by leepc12** [comment]
Hello Rob,

1. I just added `-extra_param_bwt2 "[EXTRA_PARAMS]"` so that you can freely
add any additional parameters that you want to use. Please don't forget to
quote `[EXRTA_PARAMS]`.

2. Yes, chrM is also removed when duplicates are removed. Please see
https://github.com/kundajelab/atac_dnase_pipelines/blob/master/modules/postalign_bam.bds#L210
(for SE data set) and
https://github.com/kundajelab/atac_dnase_pipelines/blob/master/modules/postalign_bam.bds#L351
(for
PE). Please remove `| grep -v 'chrM'`. But chrM will still be removed in
the final stage of the pipeline (IDR, naive-overlap and blacklist
filtering).

If you want to keep all chrM, please remove all grep -v "chrM" commands
from the following files.

https://github.com/kundajelab/atac_dnase_pipelines/blob/master/modules/postalign_bam.bds
https://github.com/kundajelab/atac_dnase_pipelines/blob/master/modules/postalign_bed.bds
.

And then replace `grep -P 'chr[\dXY]+[ \t]'` with `grep -P 'chr[\dMXY]+[
\t]'` for the following files.

https://github.com/kundajelab/atac_dnase_pipelines/blob/master/modules/callpeak_idr.bds
.
https://github.com/kundajelab/atac_dnase_pipelines/blob/master/modules/callpeak_naive_overlap.bds
.
https://github.com/kundajelab/atac_dnase_pipelines/blob/master/modules/callpeak_blacklist_filter.bds
.

Thanks,

Jin

**Comment by rbronste** [comment]
One further question, if I invoke the -no_dup_removal flag, will this impact the removal of mitochondrial reads and blacklisted sites? Thanks.

**Comment by rbronste** [comment]
Hi Jin,

Quick question, ran the pipeline in the following way and got the following error after each replicate stage (3 PE replicates) finished, and wound up with no QC:

`bds atac.bds -species mm10 -nth 16 -mapq_thresh 20 -no_dup_removal 1 -chrsz /sonas-hs/tollkuhn/hpc_norepl/home/rbronste/mm10.chrom.sizes -gensz mm`

Gpr.reader(565):	File not found '/mnt/grid/tollkuhn/hpc_norepl/home/data/rbronste/atac_dnase_pipelines/out/qc/rep1/298765_S1_R1_001_dedup.trim.PE2SE.nodup.pbc.qc'
Fatal error: modules/log_parser.bds, line 244, pos 34. Trying to access element number 0 from list 'arr' (list size: 0).

```
Creating checkpoint file: Config or command line option disabled checkpoint file creation, nothing done.
Fatal error: modules/ENCODE_accession.bds, line 184, pos 25. Map 'map_pbc' does not have key 'PBC1'.

Creating checkpoint file: Config or command line option disabled checkpoint file creation, nothing done.
Fatal error: atac.bds, line 385, pos 2. Task/s failed.

Creating checkpoint file: Config or command line option disabled checkpoint file creation, nothing done.
```
